name: Cross Browser Tests
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu_tests:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - name: Run dist
        run: node build-system/pr-check/cross-browser-tests.js
      - name: Run unit tests  
        run: node build-system/pr-check/cross-browser-tests-1.js
      - name: Run integration tests
        run: node build-system/pr-check/cross-browser-tests-2.js
  # windows_tests:
  #   name: Windows Tests
  #   runs-on: windows-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: yarn
  #     - run: node build-system/pr-check/cross-browser-tests.js
  macos_tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}        
      - run: yarn global add gulp-cli
      - name: Run dist
        run: node build-system/pr-check/cross-browser-tests.js
      - name: Run unit tests  
        run: node build-system/pr-check/cross-browser-tests-1.js
      - name: Run integration tests
        run: node build-system/pr-check/cross-browser-tests-2.js
